### ISSUE TITLE
ADS1115 returns -1 

### ISSUE THREAD

**Issue by Gorgar91** [top-gun/SMT50-ESP#4]
Hi, 
in first, thanks for great idea and solution for that ! 

in second, have small issue here, which i hope I will solve ... what ever i do, your code return me as results for voltage reads -1 , when i used esp easy , ads working fine, get results, also when i used ads basic Arduino example , I do get correct results .. is very strange to me as your code looks identical .. no special stuff regarding that ADS, I was into,  my ads is broken, but it works with other code ?!  ... only difference is, they put readings in loop part and you have it in setup, even i put it down into loop, turn off sleep , still get results -1 , any clue why ? what can be wrong ? ordered another ADS1115 just to try it , even i dont believe is broken ...  please advise.

+question - soil moisture  - when do you start your irrigation on which percentage ? and when do you stop it ? how deep you put sensor ? 

this one is working fine : i do not see difference :( 
[sketch_jul25b.txt](https://github.com/top-gun/SMT50-ESP/files/4981101/sketch_jul25b.txt)

**Comment by top-gun** [comment]
Hi Gorgar91, 

did you pull a release or the master? I recently discovered one inconsistency between wiring and code. The wiring plan does not connect the address-pin to any of the options, so it's set to the default address. My sketch was written for a different address.

This was changed for "master", which works correctly at the default address 0x48.

My older releases are coded for address 0x4a. 

Regarding the irrigation questions: This is absolutely dependant on the soil type. I start at 10-12% moisture, depending on the expected daily high temperature. For my soil, 10% moisture is close to the wilting point where the remaining water can't be extracted by the roots. This is for a soil that classifies as sandy loam. Depending on your soil, the wilting point will be different for you. In sand, it's at a lower percentage. In clay, it can be as high as 20-25%.

While it's good to start irrigation based on sensor data, don't try this for the length of the irrigation. Soil sensors are notoriously slow, as the water needs time to penetrate the root zone. There is a lot of math on the amount of water a soil can acccept in the root zone of your plants. For cold season grasses, I go by a root-zone of 4", and that means one irrigation should be 10-15mm of water or 10-15 litres per square meter.

**Comment by Gorgar91** [comment]
Hi, 
I do apologize for late reply on this, I finally get it working ! , very happy about it . .. i did replace ADS by different one - was a trick to solve, even was very strange to me as on basic sketch "old" one worked also.. anyway thanks for help and info about your timing ! will keep an aye on it for while, then i will check what is correct % for my soil .. so far is 50% as i seed just few days ago :)
