### ISSUE TITLE
Sensor04-Truebner-SMT50.ino

### ISSUE THREAD

**Issue by mat130780** [top-gun/SMT50-ESP#6]
Interessantes Projekt! Mir ist noch nicht ganz klar, wohin [dieser Code](https://github.com/top-gun/SMT50-ESP/blob/master/Wemos/Sensor04-Truebner-SMT50.ino) kopiert werden soll. Ich habe meinen Wemos D1 bereits mit Tasmota geflasht und vor dem Kompilieren den ADS1115 aktiviert. Muss ich den Code vor dem Kompilieren irgendwo einfügen?

**Comment by top-gun** [comment]
Kennst Du die Arduino Programmieroberfläche? Da kommt der Code rein, und wird von dem Programm auch auf den Wemos geflasht. Tasmota macht man anders, da gibt es fertig kompilierte Dateien. Bevor Du das hier umsetzen kannst, musst Du dich mit der Arduino-Entwicklungsumgebung befassen. Kein Hexenwerk, es gibt viele gute Guides im Web.
