### ISSUE TITLE
connection to mqtt

### ISSUE THREAD

**Issue by Matt77CHE** [top-gun/SMT50-ESP#8]
Hallo und guten Morgen

Ich hab da  mal ne Frage;

Meine mqtt -Geschichte läuft mit Benutzernamen & Pw; dies kann im code jedoch nicht hinterlegt werden..
? kann ich bei const char* mqtt_server =...... einfach noch zwei Linien einfügen mit dem Bn & dem Pw ? (wenn ja, - wie?)

... muss man bei der IP Adresse des mqtt servers den Port nicht angeben?

Habe ich dann, wenn alles funktioniert im iobroker in den Objekten unter sonoff; shelly oder so ein neues Objekt mit dem ich weiterarbeiten kann?
Wie du siehst, bin ich nicht gerade der pro auf diesem Gebiet...

Freundliche Grüsse
Matthias

**Comment by Matt77CHE** [comment]
.. update 1;
die Angabe über den Port habe ich weiter unten im code gefunden;

**Comment by top-gun** [comment]
Dafür gibt es direkt beim Pubsubclient (der verwendete Library) ein Beispiel:

https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_auth/mqtt_auth.ino
